Edited Logout
milkyway1170/my_favorite_movies_frontend pull request #10
Opened 2022-05-05 14:21 UTC by milkyway1170

2022-05-11 08:01 UTC, reshetov approved these changes

2022-05-11 10:37 UTC, Isidora25 requested changes

2022-05-11 10:37 UTC, Isidora25 commented on src/components/addFavoriteMovies/SaveItButton.tsx
> +  } = useQuery(GET_FAVORITE_MOVIES_LIST);
Очень странно, что все эти запросы у тебя обрабатываются в кнопке, которой айдишник приходит сверху 
Логичнее изолировать в кнопке только кнопку и ничего больше, а всю логику и обработку данных вынести выше

2022-05-11 10:37 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchSettings.tsx
> +    []
Тебе не нужен стейты для здесь уже, все теперь зависит от данных, приходящих с бэка

2022-05-11 10:37 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchSettings.tsx
> +  if (loadingGenres) return <div> {t("Loading...")}</div>;
Да используй один лоадинг для всех запросов

2022-05-11 10:37 UTC, Isidora25 commented on src/components/addFavoriteMovies/addFavoriteMoviesFunctions.ts
> +  const result = genresList.filter((genreItem: IGenreItem) => {
Та же самая ситуация, пусть бэк тебе сразу отдает, кто есть в фейворитс, а кто нет

2022-05-11 10:37 UTC, Isidora25 commented on src/components/mainPage/GenresTagCloud.tsx
> +      setFavoriteGenresIdList(
Тоже лишние стейты

2022-05-11 10:37 UTC, Isidora25 commented on src/components/mainPage/GenresTagCloud.tsx
> +  if (loadingGenres) return <div> {t("Loading...")}</div>;
Один лоадинг для всех сделай

2022-05-11 10:37 UTC, Isidora25 commented on src/components/mainPage/movies/MovieItem.tsx
> +      setMovieData({
Лишний стейт

2022-05-11 10:37 UTC, Isidora25 commented on src/components/mainPage/movies/MovieItem.tsx
> +  if (loadingMovieData) return <div> {t("Loading...")}</div>;
Лоадинг сделай общим, везде одно и то же 
Как и обработчик ошибок

2022-05-16 07:44 UTC, Isidora25 requested changes

2022-05-16 07:44 UTC, Isidora25 commented on .vscode/settings.json
> +{
Это точно нужно в репозитории?

2022-05-16 07:44 UTC, Isidora25 commented on package.json
> +    "react-scripts": "^4.0.0",
Понизил версию?

2022-05-16 07:44 UTC, Isidora25 commented on src/components/addFavoriteMovies/Rating.tsx
> +          activeThumb: number
А этот параметр нигде не используется

2022-05-16 07:44 UTC, Isidora25 commented on src/components/addFavoriteMovies/Rating.tsx
> +          event: Event,
если параметр обязательный, но не используется, его можно переименовать как `_ `

2022-05-16 07:44 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchedGenresTagCloud.tsx
> +    localStorage.setItem("favoriteGenres", JSON.stringify(resultList));
А зачем тебе локал сторадж опять?

2022-05-16 07:44 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchedGenresTagCloud.tsx
> +  if (loadingGenresList) return <LoadigStyles> {t("Loading...")}</LoadigStyles>;
Сделай лоадинг отдельным компонентом
Текст нигде не меняется, стили тоже
Я вроде в предыдущих комментариях упоминала об этом

2022-05-16 07:44 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchedMovieItem.tsx
> +}): any => {
Избавься от any пожалуйста

2022-05-16 07:44 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchedMovieItem.tsx
> +  if (!id) return;
И юзер увидит пустой экран?

2022-05-16 07:51 UTC, milkyway1170 commented on src/components/addFavoriteMovies/Rating.tsx
> +          activeThumb: number
Это особенность компонента из mui, он ни в какую не хочет без этого работать, доку смотрел, тщетно.

2022-05-16 12:22 UTC, Isidora25 requested changes

2022-05-16 12:22 UTC, Isidora25 commented on src/components/mainPage/movies/MovieItem.tsx
> +    return <LoadigStyles>{t("Loading...")}</LoadigStyles>;
Пропустил Loading

2022-05-16 12:57 UTC, Isidora25 approved these changes

2022-05-16 12:57 UTC, merged