Main page
milkyway1170/my_favorite_movies_frontend pull request #4
Opened 2022-03-29 08:07 UTC by milkyway1170

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +const GetMoviesList: FC<IGetMoviesList> = ({ year, rating, genres }) => {
Этот запрос отдаст только первую страницу, посмотри еще параметр page им можно их переключать

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +    .catch((data) => {
просто {} отдавай

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +    .then((data) => {
Это не нужно

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +      .then((response) => {
Стразу тут сделай преобразования, зачем еще один then, если выпадет catch просто отдай {} или []

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +interface IGetMovieData {
Вытащи в типы лучше

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +      .then((data) => {
не надо

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +const GetData = (param: string) => {
getData

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +const GetData = (param: string) => {
И может разбить на нужные тебе данные getMovies, getGenres и т.п.

2022-03-29 10:57 UTC, reshetov commented on src/components/GetFunctions.tsx
> +const LoadData = () => {
loadData

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/GenresTagCloud.tsx
> +const GenresTagCloudStyles = styled.div`
вытащи в styles.tsx и положи рядом

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/GenresTagCloud.tsx
> +const GenreItemStyles = styled.div<{ isFavorite: boolean }>`
см. выше

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/GenresTagCloud.tsx
> +    GetGenresList()
Не, лучше переделай так чтобы у тебя данные стразу приходили а не промис и тут уже их пихай в переменные

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/GenresTagCloud.tsx
> +      localStorage.setItem(
У тебя эта часть повторяется в обоих частях условия, проще переделать просто условие на тернарник
favoriteGenresList.indexOf(genreItem.name) > 0 ? favoriteGenresList.splice(index, 1) : favoriteGenresList.push(genreItem.name)
и потом уже просто сохранить

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/Greeting.tsx
> +const GreetingStyles = styled.div`
см.выше

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/Greeting.tsx
> +        {GetData("login")}
getData

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/Header.tsx
> +const HeaderStyles = styled.header`
см.выше про стили

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/Logout.tsx
> +const LogoutStyles = styled.div`
Вообще тут и далее

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/movies/MovieItem.tsx
> +  if (!movieData || typeof movieData === "undefined") return null;
!movieData достаточно и просто return без null

2022-03-29 10:57 UTC, reshetov commented on src/components/mainPage/movies/MovieItem.tsx
> +      <h3>{props.index.toString() + ". " + movieData.title}</h3>
Не нужно индекс, просто title используй

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +    var result = false;
if verifyData[login].password != password retrun false и все

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +      console.log(login);
Не нужно в коде console.log оставлять

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +    CheckUsersData();
У тебя каждый раз инициализация данных, делай ее один раз при взлете приложения (где-нибудь в App) и все

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +      alert("Your login and password is incorrect");
Не надо alert не пугай пользователя. Отдавай false и уже на основе этого рисуй блок с ошибкой на форме

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +              lableText={t("Имя пользователя или email")}
В локаль

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +            <SingInInput name="password" lableText={t("Пароль")} />
В локаль

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +              <RememberMe />
Зачем оно? Все равно не работает

2022-03-29 10:57 UTC, reshetov commented on src/components/signIn/media/.prettierrc.js
> +  printWidth: 100, // 代码宽度建议不超过100字符
ШТА?

2022-03-29 10:59 UTC, milkyway1170 commented on src/components/signIn/media/.prettierrc.js
> +  printWidth: 100, // 代码宽度建议不超过100字符
Я сам в шоке ахаха

2022-03-30 07:21 UTC, milkyway1170 commented on src/components/GetFunctions.tsx
> +const GetData = (param: string) => {
Наоборот хотел сделать getData универсальной.  Если описывать отдельно  getMovies, getGenres и т.п., код такой же будет, только продублирую.

2022-03-31 10:04 UTC, reshetov commented on src/components/GetFunctions.tsx
> +    .then((data) => {
см. выше комент

2022-03-31 10:04 UTC, reshetov commented on src/components/signIn/SignIn.tsx
> +    if (
Я вроде это тоже коментил:
Зачем так сложно
verifyData  содержит или объект с пользователями или пустой объект
verifyData[login] соотвественно будет или undefined или пароль от этого пользователя
`verifyData[login] === password` - достаточно чтобы проверить есть ли пользователь (если нет будет undefined) и правильный ли у него пароль

2022-03-31 12:02 UTC, milkyway1170 commented on src/components/signIn/SignIn.tsx
> +    if (
Я рад так сделать, мне тоже не нравится вот эта конструкция, но уже дважды я пробую сделать, как ты написал и у меня ошибок нет, да, но верификация перестает работать. Все проверил, вообще не понимаю что ему не нравится...

2022-04-01 06:29 UTC, Isidora25 requested changes

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +  const response = await fetch(
Добавь try catch здесь, чтобы обработать неуспешный результат запроса

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +  const data = await response.json();
Можно сразу сделать `return await ...` без лишних переменных

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +): Promise<any> => {
Не вижу здесь какого-то возврата из функции вообще 
Any старайся не использовать, в большинстве случаев типы известны и их можно описать

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +      isFavorite: getData("favoriteGenres").includes(name) ? true : false,
includes сам по себе уже возвращает true или false

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +): Promise<any> => {
Аналогично, не вижу ни одного return из этой функции, который бы что-то возвращал

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +    .catch(() => {});
Что делает этот пустой catch здесь? 
Возвращает пустой объект? 
Для чего этот пустой объект, много ли он информации в себе несет?

2022-04-01 06:29 UTC, Isidora25 commented on src/components/GetFunctions.tsx
> +    .then((data) => {
Чему равна data если запрос вернет ошибку?

2022-04-01 07:59 UTC, Isidora25 approved these changes

2022-04-01 08:13 UTC, closed without merging