Add favorite movies
milkyway1170/my_favorite_movies_frontend pull request #6
Opened 2022-04-05 07:08 UTC by milkyway1170

2022-04-05 07:55 UTC, reshetov requested changes

2022-04-05 07:55 UTC, reshetov commented on src/components/addFavoriteMovies/SearchedMovieItem.tsx
> +  console.log(getPoster(props.movieData.poster_path));
удали

2022-04-05 07:55 UTC, reshetov commented on src/components/mainPage/movies/MovieItem.tsx
> +      <img src={getPoster(movieData.poster_path)} alt="" />
Используй camelCase

2022-04-05 07:55 UTC, reshetov commented on src/components/addFavoriteMovies/AddFavoriteMovies.tsx
> +import { MainPageStyles, MoviesBlockStyles } from "../../styles/Styles";
Лучше добавить в webpack alias и использовать его тут чем делать относительные отступы
https://adrianmanduc.medium.com/path-aliases-in-create-react-app-v4-without-ejecting-3d7ac5f2c86a
https://stackoverflow.com/questions/63067555/how-to-make-an-import-shortcut-alias-in-create-react-app

2022-04-05 07:55 UTC, reshetov commented on src/utils/getFunctions.ts
> +  if (props.page) {
Use destruction assignment, Luke!
https://learn.javascript.ru/destructuring-assignment

2022-04-05 10:13 UTC, Isidora25 requested changes

2022-04-05 10:13 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchedMoviesList.tsx
> +        index={index + 1}
А что за индекс? Не нашла, где это используется в компоненте

2022-04-05 10:13 UTC, Isidora25 commented on src/components/mainPage/GenresTagCloud.tsx
> +    }
Где-то я уже видела этот код
https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself
Если код повторяется, значит его нужно выносить в модуль, который можно переиспользовать в несокльких местах

2022-04-05 10:13 UTC, Isidora25 commented on src/components/mainPage/movies/MovieItem.tsx
> +    id: 0,
id: 0 - это вполне конкретный id, 
лучше используй здесь пустое значение для всего объекта фильма - null, например

2022-04-05 10:13 UTC, Isidora25 commented on src/components/mainPage/movies/MoviesBlock.tsx
> +      <FirstStringStyles>
FirstStringStyles - это название для стилей, но не для компонента

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
> +      ${tw`flex flex-row items-center space-x-4`}
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
>        ${tw`w-12 rounded-md p-1`}
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
> +`;
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
> +  }
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
> +  }
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
> +    }
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/styles/Styles.tsx
> +`;
Не нужно использовать такую сложную вложенность
Можно же обстилить сразу этот тег в отдельном styledComponent

2022-04-05 10:13 UTC, Isidora25 commented on src/utils/getFunctions.ts
> +    filterUrlPart += "&primary_release_year=" + props.year?.toString();
if (props.year) уже предостерегает тебя от отсутствия пропса year и оператора ?. лишний

2022-04-05 10:13 UTC, Isidora25 commented on src/utils/getFunctions.ts
> +const getMoviesList: FC<IGetMoviesList> = (props) => {
Почему хелпер для получения данных от апи - это функциональны компонет? 
Что здесь рендерится?

2022-04-05 10:13 UTC, Isidora25 commented on src/utils/getFunctions.ts
> +        { id, title, overview, poster_path}: { id: string; title: string; overview: string; poster_path:string }
Тип вынеси в отдельный интерфейс

2022-04-05 10:13 UTC, Isidora25 commented on src/utils/getFunctions.ts
>          data.genres.map(({ id, name }: { id: string; name: string }) => ({
в отдельный тип

2022-04-08 07:31 UTC, milkyway1170 commented on src/styles/Styles.tsx
> +`;
Это готовый компонент Slider из mui, я не смог иначе обратиться к span...

2022-04-08 07:45 UTC, Isidora25 commented on src/styles/Styles.tsx
> +`;
👍

2022-04-08 08:12 UTC, Isidora25 requested changes

2022-04-08 08:12 UTC, Isidora25 commented on src/components/addFavoriteMovies/SaveItButton.tsx
> +      const resultList = checkAndChange({
А поменять что? 
Очень непонятно, что делает этот хелпер без захода в него

2022-04-08 08:12 UTC, Isidora25 commented on src/components/addFavoriteMovies/SearchedMovieItem.tsx
> +        src={getPoster(movieData.posterPath)}
Деструктурируй movieData тут тоже

2022-04-08 08:12 UTC, Isidora25 commented on src/styles/Styles.tsx
> +const SignInStyles = styled.main.attrs({
А тебе самому удобно все стили хранить в одном месте?)
Даже для твоего маленького приложения простыня уже приличная
Стайлед компоненты для этого и нужны, что ты можешь изолировать стили там, где тебе нужно 
Так что крайне рекомендую разнести их по соответствующим компонентам

2022-04-08 08:12 UTC, Isidora25 commented on src/App.tsx
> +import { MainPage } from "components/mainPage/MainPage";
Алиас создал, а не используешь?)

2022-04-08 08:12 UTC, Isidora25 commented on src/utils/getFunctions.ts
> +const getReleaseYearsList = () => {
Опять у тебя один файл содержит в себе зоопарк всех функций на проекте 
Нужно разбить на меньшие файлы

2022-04-08 08:12 UTC, Isidora25 commented on src/utils/getFunctions.ts
> +    year++
Что тут происходит с форматированием кода? x__x
Почему for на три строки убежал?

2022-04-08 08:12 UTC, Isidora25 commented on src/components/addFavoriteMovies/ReleaseYear.tsx
> +  const yearsList = getReleaseYearsList().map((year: number) => (
По сути мало что поменялось, все так же каждый рендер ты создаешь массив лет 
Сделай это один раз в хелпере и возвращай из него сразу готовый массив

2022-04-08 08:12 UTC, Isidora25 commented on src/utils/getFunctions.ts
> +    : (resultList = [...checkedArray, checkedArrayItem]);
А зачем ты делаешь дважды присваивание здесь? 
делай свои проверки сразу после присваивания 
resultList = ... ? ... : ...

2022-04-11 10:23 UTC, reshetov requested changes

2022-04-11 10:23 UTC, reshetov commented on src/components/addFavoriteMovies/SaveItButton.tsx
> +    setIsSave(!isSave);
А точно эту строку в условие не нужно? А то как-то странно получается, флажок ты переключаешь, а под капотом ничего не происходит. Если я прав, то стоит сразу guard сделать
if (!Movie) { return } 
.... тут все остальное

2022-04-11 11:19 UTC, merged